use_frameworks!

target 'KochavaEngagementExtensioniOS_Example' do
  pod 'KochavaEngagementExtensioniOS', :path => '../'
  
  target 'NotificationServiceExtension' do
      inherit! :search_paths
      pod 'KochavaEngagementExtensioniOS', :path => '../'
      
      
  end
end
