use_frameworks!

target 'KochavaEngagementExtensioniOS_Example' do
  pod 'KochavaEngagementExtensioniOS', :path => '../'

  target 'KochavaEngagementExtensioniOS_Tests' do
    inherit! :search_paths

    
  end
end
